# File: tec/ecommerce/products/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProductViewSet, CategoryViewSet, ProductSearchAPIView

# 1. Create a router instance
router = DefaultRouter()

# 2. Register ViewSets with the router
# This creates routes for standard CRUD operations: /list/, /list/{pk}/
router.register(r'list', ProductViewSet, basename='product') 

# This creates routes for standard CRUD operations: /categories/, /categories/{pk}/
router.register(r'categories', CategoryViewSet, basename='category')

# 3. Combine router URLs with custom path URLs
urlpatterns = [
    # Custom path for advanced product search
    # Example URL: /api/products/search/?q=keyword
    path(
        'search/', 
        ProductSearchAPIView.as_view(), 
        name='product_search'
    ),
    
    # Include all paths generated by the DefaultRouter (list/ and categories/)
    path('', include(router.urls)), 
]
